name: Run tests and coverage
on:
  push:
    branches:
      - '*'

jobs:
  build-tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt install -y ninja-build

      - name: Install latest Cmake
        uses: lukka/get-cmake@latest

      - name: Build cmake for tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -G Ninja \
            -B ./cmake-build-debug

      - name: Build tests
        run: |
          cmake --build ./cmake-build-debug \
            --target MonopolyAITests \
            -j 10

      - name: Run tests
        run: ./cmake-build-debug/MonopolyAITests

      - name: Build cmake for coverage
        run: |
          cmake -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -B ./cmake-build-debug-coverage

      - name: Build coverage
        run: |
          cmake --build ./cmake-build-debug-coverage \
            --target MonopolyAITests \
            -j 10

      - name: Run coverage
        run: ./cmake-build-debug-coverage/MonopolyAITests

      - name: Generate coverage report
        run: |
          lcov --capture --directory ./cmake-build-debug-coverage/CMakeFiles/MonopolyAITests.dir/ --output-file coverage.info
          lcov --list coverage.info
          genhtml coverage.info --output-directory coverage-report

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage-report
